version: '3.1'

services:

  mongo:
    image: mongo:5.0.2
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: example
    ports: 
      -  "27017:27017"

  mongo-express:
    image: mongo-express:0.54.0
    ports:
      - "8081:8081"