const order1 = {
  status: "pending",
  customerName: "Htun Htun",
  deliveryPhNumber: "0912321232",
  address: {
    houseOrApartmentNo: "121",
    streetNo: "Sanda Street",
    quarter: "40 qtr",
    township: "Yankin",
    city: "Yangon",
  },
  deliveryDate: "2021-10-15",
  paymentMethod: "cash",
  promoCode: null,
  note: "",
  products: [
    {
      productId: "617fbe201f27f23a9adfe076",
      name: "Chicken Leg",
      description: "Good for Health",
      priceUnit: "EA",
      price: 1000,
      image: `${process.env.url}/images/Chicken Leg.jpg`,
      qty: 5,
    },
    {
      productId: "617fbe201f27f23a9adfe079",
      name: "Apple",
      description: "Good for Health",
      priceUnit: "EA",
      price: 500,
      image: `${process.env.url}/images/Apple.jpg`,
      qty: 10,
    },
    {
      productId: "617fbe201f27f23a9adfe07d",
      name: "Gold Label",
      description: "Good for Health",
      priceUnit: "EA",
      price: 30000,
      image: `${process.env.url}/images/Gold Label.jpg`,
      qty: 3,
    },
  ],
};

const order2 = {
  status: "pending",
  customerName: "Mg Hla",
  deliveryPhNumber: "091233432123",
  address: {
    houseOrApartmentNo: "100",
    streetNo: "U Cho Street",
    quarter: "10 qtr",
    township: "Tamwe",
    city: "Yangon",
  },
  deliveryDate: "2021-10-11",
  paymentMethod: "cash",
  promoCode: null,
  note: "morning time only",
  products: [
    {
      productId: "617fbe201f27f23a9adfe076",
      name: "Chicken Leg",
      description: "Good for Health",
      priceUnit: "EA",
      price: 1000,
      image: `${process.env.url}/images/Chicken Leg.jpg`,
      qty: 5,
    },
    {
      productId: "617fbe201f27f23a9adfe079",
      name: "Apple",
      description: "Good for Health",
      priceUnit: "EA",
      price: 500,
      image: `${process.env.url}/images/Apple.jpg`,
      qty: 10,
    },
    {
      productId: "617fbe201f27f23a9adfe07d",
      name: "Gold Label",
      description: "Good for Health",
      priceUnit: "EA",
      price: 30000,
      image: `${process.env.url}/images/Gold Label.jpg`,
      qty: 3,
    },
  ],
};

const confirmedOrder = {
  status: "confirm",
  customerName: "Ma Saint",
  deliveryPhNumber: "09342934632",
  address: {
    houseOrApartmentNo: "1",
    streetNo: "Pyin Ya Street",
    quarter: "15 qtr",
    township: "Mayankone",
    city: "Yangon",
  },
  deliveryDate: "2021-12-11",
  paymentMethod: "cash",
  promoCode: null,
  note: "",
  products: [
    {
      productId: "617fbe201f27f23a9adfe076",
      name: "Chicken Leg",
      description: "Good for Health",
      priceUnit: "EA",
      price: 1000,
      image: `${process.env.url}/images/Chicken Leg.jpg`,
      qty: 10,
    },
    {
      productId: "617fbe201f27f23a9adfe079",
      name: "Apple",
      description: "Good for Health",
      priceUnit: "EA",
      price: 500,
      image: `${process.env.url}/images/Apple.jpg`,
      qty: 1,
    },
    {
      productId: "617fbe201f27f23a9adfe07d",
      name: "Gold Label",
      description: "Good for Health",
      priceUnit: "EA",
      price: 30000,
      image: `${process.env.url}/images/Gold Label.jpg`,
      qty: 4,
    },
  ],
};

const completedOrder = {
  status: "complete",
  customerName: "Mg Mg",
  deliveryPhNumber: "09234231232",
  address: {
    houseOrApartmentNo: "1",
    streetNo: "Pyin Ya Street",
    quarter: "15 qtr",
    township: "Mayankone",
    city: "Yangon",
  },
  deliveryDate: "2021-12-11",
  paymentMethod: "cash",
  promoCode: null,
  note: "",
  products: [
    {
      productId: "617fbe201f27f23a9adfe076",
      name: "Chicken Leg",
      description: "Good for Health",
      priceUnit: "EA",
      price: 1000,
      image: `${process.env.url}/images/Chicken Leg.jpg`,
      qty: 5,
    },
    {
      productId: "617fbe201f27f23a9adfe079",
      name: "Apple",
      description: "Good for Health",
      priceUnit: "EA",
      price: 500,
      image: `${process.env.url}/images/Apple.jpg`,
      qty: 2,
    },
    {
      productId: "617fbe201f27f23a9adfe07d",
      name: "Gold Label",
      description: "Good for Health",
      priceUnit: "EA",
      price: 30000,
      image: `${process.env.url}/images/Gold Label.jpg`,
      qty: 3,
    },
  ],
};

export default [order1, order2, confirmedOrder, completedOrder];
